# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau21-grupp4-4d9plfkz634h.sprinto.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept


POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Lemon posset med hallon",
    "description": "Lemon posset är en brittisk dessert gjord på grädde smaksatt med citron och påminner om italiensk pannacotta men utan gelatin. En krämig efterrätt med perfekt balans mellan syra och sötma som är både löjligt enkel och löjligt god!",
    "ratings": [],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_243039/cf_259/lemon_posset_med_hallon.jpg",
    "timeInMins": 60,
    "categories": "Efterrätt",
    "instructions": [ "Koka upp grädde och socker, låt koka 1 minut. Ta från värmen och rör ner citronjuice.", 
"Häll upp i 6 formar eller glas (för 6 port) och ställ i kylen minst 4 timmar eller tills de stelnat.", 
"Till servering: Toppa med hallon vid servering."],
    "ingredients": [
        {
            "name": "VispGrädde",
            "amount": 5,
            "unit": "dl"
        },
        {
            "name": "Strösocker",
            "amount": 1.5,
            "unit": "dl"
        },
        {
            "name": "Färskpressad citronjuice",
            "amount": 0.75,
            "unit": "dl"
        },
        {
            "name": "Förp färska hallon",
            "amount": 125,
            "unit": "g"
        }
        
    ]
}

###

# Lägger till ett nytt recept

POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Lemon posset med hallon",
    "description": "Lemon posset är en brittisk dessert gjord på grädde smaksatt med citron och påminner om italiensk pannacotta men utan gelatin. En krämig efterrätt med perfekt balans mellan syra och sötma som är både löjligt enkel och löjligt god!",
    "ratings": [],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_243039/cf_259/lemon_posset_med_hallon.jpg",
    "timeInMins": 60,
    "categories": "Efterrätt",
    "instructions": [ "Koka upp grädde och socker, låt koka 1 minut. Ta från värmen och rör ner citronjuice.", 
"Häll upp i 6 formar eller glas (för 6 port) och ställ i kylen minst 4 timmar eller tills de stelnat.", 
"Till servering: Toppa med hallon vid servering."],
    "ingredients": [
        {
            "name": "VispGrädde",
            "amount": 5,
            "unit": "dl"
        },
        {
            "name": "Strösocker",
            "amount": 1.5,
            "unit": "dl"
        },
        {
            "name": "Färskpressad citronjuice",
            "amount": 0.75,
            "unit": "dl"
        },
        {
            "name": "Förp färska hallon",
            "amount": 125,
            "unit": "g"
        }
        
    ]
}

# Lägger till ett nytt recept

POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Färsk pasta med lax och svartkål",
    "description": "Snabb, lättlagad och försvinnande god är laxpastan som görs av crème fraiche och svartkål. Låt laxbitarna koka i den goda såsen som även smaksätts med lite citron. Servera sedan laxen i såsen färsk pasta, fettuccine. Så gott!",
    "ratings": [],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_243518/cf_259/farsk_pasta_med_lax_och_svartkal___.jpg",
    "timeInMins": 30,
    "categories": "Huvudrätt",
    "instructions": [ "Tina fisken (om fryst används).", "
Sätt på en stor kastrull med vatten till pastan.", "Dra av svartkålsbladen från stjälkarna och hacka bladen grovt. Hacka stjälkarna fint.", "rör ner grädde och mjölk. Låt sjuda i 5 minuter", "
Fräs all svartkål i smöret i en stekpanna (med lock) ca 2 minuter.", "Tillsätt crème fraiche, vatten och smulad buljongtärning. Sjud på svag värme ca 5 minuter.", "
Hacka salladslöken fint och basilikan grovt.", "
Riv yttersta skalet av citronen och pressa ur citronsaften. Smaksätt kålsåsen med citronskal, citronsaft, salt och peppar.", "
Lägg laxbitarna i såsen och sjud under lock i 2-3 minuter eller tills laxen har en innertemperatur på 54°C.", "Koka pastan enligt anvisningen på förpackningen.", "
Strö salladslöken och basilika över laxen och servera tillsammans med pastan."],
    "ingredients": [
        {
            "name": "Svartkål",
            "amount": 200,
            "unit": "g"
        },
        {
            "name": "Smör",
            "amount": 2,
            "unit": "msk"
        },
        {
            "name": "Crème fraiche",
            "amount": 2.5,
            "unit": "dl"
        },
        {
            "name": "Vatten",
            "amount": 2,
            "unit": "dl"
        },
        {
            "name": "Grönsaksbuljongtärning",
            "amount": 1,
            "unit": "st"
        },
        {
            "name": "citron",
            "amount": 1,
            "unit": "st"
        },
         {
            "name": "Basilika",
            "amount": 1,
            "unit": "kruka"
        },
         {
            "name": "Salt",
            "amount": 0.5,
            "unit": "kruka"
        },
         {
            "name": "Svartpeppar",
            "amount": 3,
            "unit": "kmr"
        },
         {
            "name": "Laxfilé",
            "amount": 4,
            "unit": "st"
        },
         {
            "name": "fettuccine",
            "amount": 2,
            "unit": "förp"
        }
    ]
}




###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=pizza HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/633bdd8b91dc8ff8a20cfa7d HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1
Content-Type: application/json

{
  "description": "Gott till apelsinsaft"
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Förrätt/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=brus HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/632da30c6e7766b37d983811/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/633bf45591dc8ff8a20cfaf4/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/633bf45591dc8ff8a20cfaf4/comments
Content-Type: application/json

{
    "comment": "För mycket salt!",
    "name": "Bosse"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
