# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau21-grupp4-4d9plfkz634h.sprinto.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept


POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Fyllda Chokladkakor till halloween",
    "description": "Kakor i form av pumpor med ett dekorativt pumpamönster är perfekta för halloween. Prova dessa mumsiga chokladkakor med en fyllning av smörkräm med smak av vit choklad",
    "ratings": [0],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_243969/cf_259/fyllda_chokladkakor_till_halloween.jpg",
    "timeInMins": 60,
    "categories": "Desert",
    "instructions": ["Vispa smör, socker och hushållsfärg krämigt med elvisp i en bunke. Tillsätt ett ägg i taget under fortsatt vispning. Sikta ner salt, mjöl och kakao och vispa ihop till en deg. Degen blir först smulig, fortsätt vispa tills den går ihop. Plasta degen och lägg i kylen minst 1 timme.","Gör en mall i form av en pumpa (ca 4-5 cm i diameter) av lite tjockare papper. Kavla ut degen till en ca 3 mm tjock platta på en mjölad bänk. Skär ut 30 kakor enligt mallen och lägg på 2 bakpappersklädda plåtar (för 15 kakor). Grädda en plåt i taget 10-12 minuter. Låt svalna.","Smält chokladen i en bunke över ett vattenbad eller i micron. Vispa ihop smör, florsocker och vaniljsocker och tillsätt chokladen. Vispa till en slät kräm. Fyll i en spritspåse. Spritsa ca hälften av fyllningen på hälften av kakorna. Lägg på resten av kakorna och tryck försiktigt ihop. Spritsa sedan ett pumpamönster på kakorna med resten av fyllningen."],
    "ingredients": [
        {
            "name": "rumstempererat smör",
            "amount": 300,
            "unit": "g"
        },
        {
            "name": "Strösocker",
            "amount": 3,
            "unit": "dl"
        },
        {
            "name": "Svart hushållsfärg",
            "amount": 1.5,
            "unit": "msk"
        },
        {
            "name": "ägg",
            "amount": 2,
            "unit": "st"
        },
        {
            "name": "salt",
            "amount": 1.5,
            "unit": "tsk",
        },
        {
            "name": "vetemjöl",
            "amount": 5,
            "unit": "dl",
        },
        {
            "name": "kakao",
            "amount": 2,
            "unit": "dl",
        },
        {
            "name": "vit choklad",
            "amount": 100,
            "unit": "g",
        },
        {
            "name": "florsocker",
            "amount": 2,
            "unit": "dl",
        },
        {
            "name": "vaniljsocker",
            "amount": 1,
            "unit": "msk",
        }
    ]
}

###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=pizza HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/633ec10091dc8ff8a20d015f HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1
Content-Type: application/json

{
  "description": "Gott till apelsinsaft"
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Förrätt/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=brus HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/633bf45591dc8ff8a20cfaf4/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/633bf45591dc8ff8a20cfaf4/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/633bf45591dc8ff8a20cfaf4/comments
Content-Type: application/json

{
    "comment": "För mycket salt!",
    "name": "Bosse"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
